app:
  host: "localhost"
  port: 8000
db:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "postgres"
  db_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@example.com"
  authorization_token: "secret-token"
  timeout_milliseconds: 10000
